services:
  publish:
    image: ghcr.io/anon1y4012/publish:latest
    container_name: publish
    environment:
      PUBLISH_TOKEN: "change-me"
      PUBLISH_PORT: "8765"
      PUBLISH_HOST: "0.0.0.0"
      PUBLISH_SECRET_KEY: "change-me-too"
    volumes:
      - /Users/USERNAME/publish:/inbox
    ports:
      - 8765:8765
    restart: unless-stopped
